#!/usr/bin/env bash

# This script is idempotent.

set -euxo pipefail

CHAIN=$1
DOMAIN=$2
BRANCH=$3
COMMIT=$4
REVISION="dog-$BRANCH-$COMMIT"

export DEBIAN_FRONTEND=noninteractive

touch ~/.hushlogin

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  clang \
  curl \
  libsqlite3-dev\
  libssl-dev \
  locales-all \
  pkg-config \
  ufw \
  vim

apt-get remove --yes --auto-remove

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    COOKIE_FILE_DIR=/var/lib/dogecoind
    CSP_ORIGIN=doginals.com
    ufw allow 8333
    ;;
  regtest)
    COOKIE_FILE_DIR=/var/lib/dogecoind/regtest
    CSP_ORIGIN=regtest.doginals.com
    ufw allow 18444
    ;;
  signet)
    COOKIE_FILE_DIR=/var/lib/dogecoind/signet
    CSP_ORIGIN=signet.doginals.com
    ufw allow 38333
    ;;
  test)
    COOKIE_FILE_DIR=/var/lib/dogecoind/testnet3
    CSP_ORIGIN=testnet.doginals.com
    ufw allow 18333
    ;;
  testnet4)
    COOKIE_FILE_DIR=/var/lib/dogecoind/testnet4
    CSP_ORIGIN=testnet4.doginals.com
    ufw allow 48333
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

mkdir -p \
  /etc/systemd/system/dogecoind.service.d \
  /etc/systemd/system/dog.service.d

OVERRIDE=/etc/systemd/system/dog.service.d/override.conf

echo '[Service]' > $OVERRIDE
echo "Environment=CHAIN=$CHAIN" >> $OVERRIDE
echo "Environment=CSP_ORIGIN=$CSP_ORIGIN" >> $OVERRIDE

if [[ $CHAIN == main ]]; then
  echo Environment=DOG_SERVER_DISABLE_JSON_API=true >> $OVERRIDE
fi

cp $OVERRIDE /etc/systemd/system/dogecoind.service.d/override.conf

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sshd -t
systemctl restart sshd

ufw --force enable

if ! command -v dogecoind > /dev/null || ! command -v dogecoin-cli > /dev/null; then
  echo "dogecoind and dogecoin-cli must already be installed." >&2
  exit 1
fi

dogecoind --version

rm -f /var/lib/dogecoind/settings.json

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
install --backup target/release/dog /usr/local/bin/dog

id --user dogecoin || useradd --system dogecoin
id --user dog || useradd --system dog

cp deploy/dogecoind.service /etc/systemd/system/

mkdir -p /etc/dogecoin
cp deploy/dogecoin.conf /etc/dogecoin/dogecoin.conf

if [[ ! -e ~/.dogecoin/dogecoin.conf ]]; then
  mkdir -p ~/.dogecoin
  ln -s /etc/dogecoin/dogecoin.conf ~/.dogecoin/dogecoin.conf
fi

systemctl daemon-reload
systemctl enable dogecoind
systemctl restart dogecoind

while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
  echo "Waiting for dogecoind..."
  sleep 1
done

setfacl -m dog:x /var/lib/dogecoind
setfacl -m dog:x $COOKIE_FILE_DIR
setfacl -dm dog:r $COOKIE_FILE_DIR
setfacl -m dog:r $COOKIE_FILE_DIR/.cookie

journalctl --unit dog --vacuum-time 1s

cp deploy/dog.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable dog
systemctl restart dog

while ! curl --fail https://$DOMAIN/status > /dev/null; do
  echo "Waiting for dog at https://$DOMAIN/status..."
  sleep 1
done
